sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vgarrido/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vgarrido/docker-react npm run test