sudo: required
language: generic
services:
  - docker

before_install:
    - docker build -t vgarrido/reactapp:latest -f ./Dockerfile.dev .

script:
  - make REACT_BUILD_DOCKERFILE
  - make REACT_RUN_TEST_DOCKERFILE_CI